### ISSUE TITLE
Please specify the license for this code

### ISSUE THREAD

**Issue by mistercrunch** [Lwangaman/jQuery-Clock-Plugin#12]
We're using this plugin for Apache Airflow and I need to know whether the license is compatible. Please let Github know what license this project is under. Usually people add a LICENSE.md file to their repo.

Thanks for this helpful plugin, this has served us well!

**Comment by Lwangaman** [comment]
ok if I understand correctly the Apache License is permissive enough to let you use the code as you like. I have added the Apache 2.0 license.
